CourseManagement/Controllers/LecturerController.cs
using CourseManagement.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseManagement.Controllers
{
    public class LecturerController : Controller
    {
        [HttpGet]
        public ActionResult AddLesson(int id)
        {
            using (var dc = new MyDatabaseEntities())
            {
                var lesson = new Topic();
                lesson.CourseId = id;
                List<Topic> lessons = dc.Topics.Where(m => m.CourseId == id).ToList();
                if (lessons.Count == 0)
                {
                    lesson.TopicNumber = 1;
                }
                else
                {
                    lesson.TopicNumber = lessons.Count + 1;
                }
                return View(lesson);
            }
        }

        [HttpPost]
        public ActionResult AddLesson(Topic lesson)
        {
            int course_id;
            using (var dc = new MyDatabaseEntities())
            {
                course_id = lesson.CourseId;
                dc.Topics.Add(lesson);
                dc.SaveChanges();
                return RedirectToAction("ViewCourse", "Course", new { id = course_id });
            }
        }

        public ActionResult ShowLessons(int id)
        {
            using (var dc = new MyDatabaseEntities())
            {
                var lessons = dc.Topics.Where(m => m.CourseId == id).ToList();
                return PartialView(lessons);
            }
        }

        [HttpGet]
        public ActionResult AddMaterial(int id)
        {
            using (var dc = new MyDatabaseEntities())
            {
                var material = dc.Materials.Where(m => m.TopicId == id).FirstOrDefault();
                if (material != null)
                {
                    return View(material);
                }
                else
                {
                    Material file = new Material()
                    {
                        TopicId = id
                    };
                    return View(file);
                }
            }
        }

        [HttpPost]
        public ActionResult AddMaterial(Material material)
        {
            int LessonId = 0;
            int CourseId = 0;
            using (var dc = new MyDatabaseEntities())
            {
                foreach (var item in material.MaterialsObj)
                {
                    if (item.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(item.FileName);
                        var path = Path.Combine(Server.MapPath("/Content/Materials"), fileName);
                        item.SaveAs(path);
                        LessonId = dc.Topics.Where(m => m.TopicId == material.TopicId).First().TopicId;
                        CourseId = dc.Topics.Where(m => m.TopicId == material.TopicId).First().CourseId;
                        Material file = new Material()
                        {
                            Path = path,
                            TopicId = LessonId,
                            Name = fileName
                        };
                        dc.Materials.Add(file);
                    }
                }
                dc.SaveChanges();
                return RedirectToAction("ViewLesson", "Course", new { lesson_id = LessonId, course_id = CourseId });
            }
        }

        [HttpGet]
        public ActionResult DeleteMaterial(int id)
        {
            using (var dc = new MyDatabaseEntities())
            {
                var material = dc.Materials.Where(m => m.TopicId == id).ToList();
                return View(material);
            }
        }

        [HttpPost]
        public ActionResult DeleteMaterial(List<Material> files)
        {
            using (var dc = new MyDatabaseEntities())
            {
                int topic_id = files.FirstOrDefault().TopicId;
                int courses_id = dc.Topics.Where(m => m.TopicId == topic_id).FirstOrDefault().CourseId;
                foreach (var item in files)
                {
                    var material = dc.Materials.Where(m => m.MaterialId == item.MaterialId).FirstOrDefault();
                    if (System.IO.File.Exists(material.Path))
                    {
                        System.IO.File.Delete(material.Path);
                    }
                    dc.Materials.Remove(material);
                }
                dc.SaveChanges();
                return RedirectToAction("ViewLesson", "Course", new { lesson_id = topic_id, course_id = courses_id });
            }
        }

        public FileResult Download(string path, string filename)
        {
            var doc = new byte[0];
            doc = System.IO.File.ReadAllBytes(path);
            return File(doc, "multipart/form-data", filename);
        }

        public ActionResult ShowMaterials(int topic_id, int course_id)
        {
            bool status = false;
            string email = User.Identity.Name;
            using (var dc = new MyDatabaseEntities())
            {
                var materials = dc.Materials.Where(m => m.TopicId == topic_id).ToList();
                int courses_id = dc.Topics.Where(m => m.TopicId == topic_id).First().CourseId;
                var course = dc.Courses.Where(m => m.CourseId == courses_id).FirstOrDefault();
                var user = dc.Users.Where(m => m.EmailId == email).FirstOrDefault();
                if (course.CourseId == course_id && course.LecturerId == user.UserId)
                {
                    status = true;
                }
                ViewBag.Status = status;
                ViewBag.TopicId = topic_id;
                return PartialView(materials);
            }
        }

        [HttpGet]
        public ActionResult AddQuiz(int id)
        {
            using (var dc = new MyDatabaseEntities())
            {
                var quiz = dc.Quizs.Where(m => m.TopicId == id).FirstOrDefault();
                if (quiz != null)
                {
                    return View(quiz);
                }
                else
                {
                    Quiz test = new Quiz()
                    {
                        TopicId = id
                    };
                    return View(test);
                }
            }
        }

        [HttpPost]
        public ActionResult AddQuiz(Quiz quiz)
        {
            using (var dc = new MyDatabaseEntities())
            {
                dc.Quizs.Add(quiz);
                dc.SaveChanges();
                return RedirectToAction("AddQuestions", new { quiz_id = quiz.QuizId });
            }
        }

        [HttpGet]
        public ActionResult AddQuestions(int quiz_id, int? question_id)
        {
            using (var dc = new MyDatabaseEntities())
            {
                var quest = dc.Questions.Where(m => m.QuizId == quiz_id && m.QuestionId == question_id).FirstOrDefault();
                if (quest == null)
                {
                    Question question = new Question()
                    {
                        QuizId = quiz_id,
                        Question1 = " "
                    };
                    Answer answer = new Answer()
                    {
                        Question_Id = question.QuestionId,
                        Label = " ",
                        IsCorrect = true
                    };
                    Answer choice = new Answer()
                    {
                        Question_Id = question.QuestionId,
                        Label = " ",
                        IsCorrect = false
                    };
                    dc.Answers.Add(choice);
                    dc.Answers.Add(answer);
                    dc.Questions.Add(question);
                    dc.SaveChanges();
                    ModelState.Clear();
                    return View(question);
                }
                else
                {
                    ModelState.Clear();
                    return View(quest);
                }
            }
        }

        [HttpPost]
        public ActionResult AddQuestions(string quest_id, string qz_id, string action, string[] allNames)
        {
            using (var dc = new MyDatabaseEntities())
            {
                int question_idd = Convert.ToInt32(quest_id);
                int quiz_idd = Convert.ToInt32(qz_id);
                var quest = dc.Questions.Where(m => m.QuestionId == question_idd).FirstOrDefault();
                quest.Question1 = allNames[0];
                if (action == "AddCorrectOption")
                {
                    var correct_answer_list = dc.Answers.Where(m => m.Question_Id == question_idd && m.IsCorrect).ToList();
                    var wrong_answer_list = dc.Answers.Where(m => m.Question_Id == question_idd && !m.IsCorrect).ToList();
                    if (correct_answer_list.Count != 0)
                    {
                        for (int i = 0; i < correct_answer_list.Count; i++)
                        {
                            correct_answer_list[i].Label = allNames[i + 1];
                        }
                        if (wrong_answer_list != null)
                        {
                            for (int i = correct_answer_list.Count + 1, j = 0; i < allNames.Length; i++, j++)
                            {
                                wrong_answer_list[j].Label = allNames[i];
                            }
                        }
                        Answer answer = new Answer()
                        {
                            Question_Id = question_idd,
                            Label = " ",
                            IsCorrect = true
                        };
                        dc.Answers.Add(answer);
                    }
                    else
                    {

CourseManagement/Views/Lecturer/AddLesson.cshtml
@model CourseManagement.Models.Topic

@{
    ViewBag.Title = "AddLesson";
}

<div class="forms" style="margin-top:25px;">
    <h2 style="margin-top:25px;">Add lesson</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.TopicNumber)
        <div class="form-horizontal">
            @Html.HiddenFor(m => m.CourseId)
            <div class="form-group">
                <label style="margin-left: 30px;" for="Name" class="col-md-12">Lesson name:</label>
                <div class="col-md-12">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="fas fa-font"></i>
                        </span>
                        @Html.EditorFor(model => model.Name)
                    </div>
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group" style="margin-left: 12%;">
                <div class="col-md-offset-2 col-md-10">
                    <input style="width: 60%;" type="submit" value="Add lesson" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
</div>
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

CourseManagement/Views/Lecturer/AddMaterial.cshtml
@model CourseManagement.Models.Material

@{
    ViewBag.Title = "AddMaterial";
}

<div class="forms" style="margin-top:25px;">
    <h2 style="margin-top:25px;">Add material(s)</h2>
    @using (Html.BeginForm("AddMaterial", "Lecturer", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.TopicId)
        <div class="form-horizontal">
            @Html.ValidationSummary(true)
            <input type="file" name="MaterialsObj" id="MaterialsObj" multiple />

            <div class="form-group" style="margin-left: 12%;">
                <div class="col-md-offset-2 col-md-10">
                    <input style="width: 60%;" type="submit" value="Add" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>

CourseManagement/Views/Lecturer/AddQuestions.cshtml
@model CourseManagement.Models.Question

@{
    ViewBag.Title = "AddQuestions";
}

<div class="forms" style="margin-top:25px; width: 65%;">
    <h2 style="margin-top: 30px;">Adding Question</h2>
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.QuizId)
    @Html.HiddenFor(m => m.QuestionId)
    <div class="form-horizontal">
        <div class="form-group">
            <label style="margin-left: 30px;" for="Name" class="col-md-12">Question title:</label>
            <div class="col-md-12">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fas fa-pen"></i>
                    </span>
                    @Html.EditorFor(model => model.Question1)
                </div>
                @Html.ValidationMessageFor(model => model.Question1)
            </div>
        </div>

        <div id="CorrectOpt">
            @{Html.RenderAction("CorrectOptions", "Quiz", new { question_id = Model.QuestionId });}
        </div>

        <div id="Opt">
            @{Html.RenderAction("Options", "Quiz", new { question_id = Model.QuestionId });}
        </div>

        <nav class="button-question-bar">
            <ul>
                <li>
                    <button style="width:150px;" type="submit" name="action" value="AddCorrectOption" class="btn btn-info" onclick="getAllNames()">
                        Add correct option
                    </button>
                </li>
                <li>
                    <button style="width:100px;" type="submit" name="action" value="AddOption" class="btn btn-info" onclick="getAllNames()">
                        Add option
                    </button>
                </li>
                <li>
                    <button style="width:250px;" type="submit" name="action" value="SaveAndAdd" class="btn btn-success" onclick="getAllNames()">
                        Save this question and add another
                    </button>
                </li>
                <li>
                    <button style="width:160px;" type="submit" name="action" value="SaveAll" class="btn btn-primary" onclick="getAllNames()">
                        Save all and cancel
                    </button>
                </li>
            </ul>
        </nav>
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        const getAllNames = () => {
            var inputed_text = document.getElementsByClassName('text-box single-line');
            inputed_text = Array.prototype.slice.call(inputed_text).map(object => { return object.value; });
            var question_id = $('#QuestionId').val();
            var quiz_id = $('#QuizId').val();
            var act = document.activeElement.getAttribute('value');
            $.ajax({
                type: "POST",
                url: '/Lecturer/AddQuestions',
                data: {
                    quest_id: question_id,
                    qz_id: quiz_id,
                    action: act,
                    allNames: inputed_text
                },
                dataType: 'json',
                traditional: true,
                success: function (response) {
                    window.location.href = response.redirectToUrl;
                }
            });
        }
    </script>
}

CourseManagement/Views/Lecturer/AddQuiz.cshtml
@model CourseManagement.Models.Quiz

@{
    ViewBag.Title = "AddQuiz";
}

<div class="forms" style="margin-top:25px;">
    <h2 style="margin-top:25px;">Create new quiz</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.TopicId)
        @Html.HiddenFor(m => m.QuizId)
        @Html.HiddenFor(m => m.IsActive)
        <div class="form-horizontal">
            <div class="form-group">
                <label style="margin-left: 30px;" for="Name" class="col-md-12">Quiz Name:</label>
                <div class="col-md-12">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="fas fa-font"></i>
                        </span>
                        @Html.EditorFor(model => model.Name)
                    </div>
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group">
                <label style="margin-left: 30px;" for="Description" class="col-md-12">Description:</label>
                <div class="col-md-12">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="fas fa-file-signature"></i>
                        </span>
                        @Html.EditorFor(model => model.Description)
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label style="margin-left: 30px;" for="DurationInMinutes" class="col-md-12">Duration:</label>
                <div class="col-md-12">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="fas fa-hourglass-start"></i>
                        </span>
                        @Html.EditorFor(model => model.DurationInMinutes)
                    </div>
                </div>
            </div>

            <div class="form-group" style="margin-left: 12%;">
                <div class="col-md-offset-2 col-md-10">
                    <input style="width: 60%;" type="submit" value="Save quiz and start adding questions" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

CourseManagement/Views/Lecturer/DeleteMaterial.cshtml
@model List<CourseManagement.Models.Material>

@{
    ViewBag.Title = "DeleteMaterial";
}

<div class="forms" style="margin-top:25px;">
    <h2 style="margin-top:25px;">Delete Materials</h2>
    <div class="form-horizontal">
        <h3 style="text-align:center">Are you sure you want to delete all lesson materials?</h3>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            for (int i = 0; i < Model.Count; i++)
            {
                @Html.HiddenFor(m => Model[i].MaterialId)
                @Html.HiddenFor(m => Model[i].TopicId)
            }
            <div class="form-group" style="margin-left: 12%;">
                <div class="col-md-offset-2 col-md-10">
                    <input style="width: 60%;" type="submit" value="Delete materials" class="btn btn-danger" />
                </div>
            </div>
        }
    </div>
</div>

CourseManagement/Views/Lecturer/DeleteQuestion.cshtml
@model CourseManagement.Models.Question

@{
    ViewBag.Title = "DeleteQuestion";
}

<div class="forms" style="margin-top:25px;">
    <h2 style="margin-top:25px;">Delete Question</h2>
    <div class="form-horizontal">
        <h3 style="text-align:center">Are you sure you want to delete this question?</h3>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.QuestionId)
            @Html.HiddenFor(m => m.QuizId)
            <div class="form-group" style="margin-left: 12%;">
                <div class="col-md-offset-2 col-md-10">
                    <input style="width: 60%;" type="submit" value="Delete question" class="btn btn-danger" />
                </div>
            </div>
        }
    </div>
</div>

CourseManagement/Views/Lecturer/ShowLessons.cshtml
@model List<CourseManagement.Models.Topic>


@if (Model.Count != 0)
{
    foreach (var item in Model)
    {
        <div class="lesson-container" onclick="location.href = '@Url.Action("ViewLesson", "Course", new { lesson_id = item.TopicId, course_id = item.CourseId })'">
            <span class="lesson-name">Lesson №@item.TopicNumber: @item.Name</span>
        </div>
    }
}
else
{
    <p>This course has no lessons.</p>
}

CourseManagement/Views/Lecturer/ShowMaterials.cshtml
@model List<CourseManagement.Models.Material>


@if (Model.Count != 0)
{
    <nav class="links-groups">
        <ul>
            @foreach (var item in Model)
            {
                <li><a href="@Url.Action("Download", new { path = item.Path, filename = item.Name})" style="text-decoration:none;">@item.Name</a></li>
            }
            @if (Convert.ToBoolean(ViewBag.Status))
            {
                <li>
                    <form action="@Url.Action("AddMaterial",  new { id = Convert.ToInt32(ViewBag.TopicId) })">
                        <button type="submit" class="btn btn-success">
                            Add materials
                        </button>
                    </form>
                </li>
                <li>
                    <form action="@Url.Action("DeleteMaterial",  new { id = Convert.ToInt32(ViewBag.TopicId) })">
                        <button type="submit" class="btn btn-danger">
                            Delete material(s)
                        </button>
                    </form>
                </li>
            }
        </ul>
    </nav>
}
else if (Convert.ToBoolean(ViewBag.Status))
{
    <p>This lesson has no materials. For adding materials go @Html.ActionLink("here.", "AddMaterial", new { id = Convert.ToInt32(ViewBag.TopicId) })</p>
}
else
{
    <p>
        This lesson has no materials.
    </p>
}

CourseManagement/Views/Lecturer/ShowQuiz.cshtml
@model CourseManagement.Models.Quiz

@if (Model != null)
{
    <table border="1" style="font-size: 15px; width: 90%; border: solid 1px #70a1ff;">
        <tr style="background: #70a1ff; color: #3742fa;">
            <th style="width: 40%;"><center>Name</center></th>
            <th><center>Duration</center></th>
            <th><center>Questions</center></th>
            <th style="width: 40%;"><center>Actions</center></th>
        </tr>
        <tr style="background: white;">
            <th><center><a href="#" style="text-decoration:none; font-size:16px; color:#20152c"><i class="fas fa-edit"></i> @Model.Name</a></center></th>
            <th><center>@Model.DurationInMinutes</center></th>
            <th><center>@ViewBag.QuestionsCount</center></th>
            <th>
                <center>
                    @if (Convert.ToBoolean(ViewBag.Status))
                    {
                        <a href="@Url.Action("QuestionsList", "Quiz", new { quiz_id = Model.QuizId })" class="btn btn-info">
                            Questions list
                        </a>
                        <a href="@Url.Action("ViewMembers", "Quiz", new { quiz_id = Model.QuizId })" class="btn btn-primary">
                            View members
                        </a>
                        <a href="@Url.Action("DeleteQuiz", "Quiz", new { quiz_id = Model.QuizId })" class="btn btn-danger">
                            Delete quiz
                        </a>
                    }
                    else
                    {
                        <a href="@Url.Action("AttemptQuiz", "Quiz", new { quiz_id = Model.QuizId })" class="btn btn-success">
                            Start quiz
                        </a>
                    }
                </center>
            </th>
        </tr>
    </table>
}
else if (Convert.ToBoolean(ViewBag.Status))
{
    <p>This lesson has no questionaries. For adding questionaries go @Html.ActionLink("here.", "AddQuiz", new { id = Convert.ToInt32(ViewBag.TopicId) })</p>
}
else
{
    <p>
        This lesson has no questionaries.
    </p>
}

CourseManagement/Views/Lecturer/ViewSubscribers.cshtml
@model List<CourseManagement.Models.User>

@{
    ViewBag.Title = "ViewSubscribers";
}

<div class="forms" style="margin-top: 25px;">
    <h2 style="margin-top: 25px;">Subscribers of @ViewBag.CourseName course</h2>
    @if (Model.Count == 0)
    {
        <div class="alert alert-info">
            <strong>Oops!</strong> This course has no subscribers.
        </div>
    }
    else
    {
        using (Html.BeginForm())
        {
            <div class="form-horizontal">
                <center>
                    <table border="1" style="font-size: 15px; width: 90%; border: solid 1px #70a1ff; margin-bottom: 30px;">
                        <tr style="background: #70a1ff; color: #3742fa;">
                            <th><center>Full Name</center></th>
                            <th><center>Email</center></th>
                            <th><center>Birth date</center></th>
                        </tr>
                        @for (int i = 0; i < Model.Count; i++)
                        {
                            if (i % 2 != 0)
                            {
                                <tr style="background: #bef7f0;"><td><center>@Html.EditorFor(m => Model[i].FullName)</center></td><td><center>@Html.EditorFor(m => Model[i].EmailId)</center></td><td><center>@Html.EditorFor(m =>Model[i].DateOfBirth)</center></td></tr>
                            }
                            else
                            {
                                <tr><td><center>@Html.EditorFor(m =>Model[i].FullName)</center></td><td><center>@Html.EditorFor(m =>Model[i].EmailId)</center></td><td><center>@Html.EditorFor(m =>Model[i].DateOfBirth)</center></td></tr>
                            }
                        }
                    </table>
                </center>
            </div>
        }
    }
</div>